image: node:19

cache:
  paths:
    - node_modules/
    - .yarn

stages: # List of stages for jobs, and their order of execution
  - build

build-job:
  stage: build
  script:
    - mission-robotics-build/build.sh
