name: Build and Publish

permissions:
  packages: write
  actions: read
  contents: read

on:
  push:
    branches:
      - mission-robotics/integration

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      JFROG_NPM_TOKEN: ${{ secrets.JFROG_NPM_TOKEN }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Setup yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Build and publish
        run: |
          bash mission-robotics-build/build.sh
